# Mergify configuration for automatic PR merging
# This will auto-merge PRs when all required status checks pass
#
# Status check names from your workflows:
# - GitHub Actions: check-success=test, check-success=deploy, check-success=Run E2E Tests
# - All checks are GitHub Actions CheckRuns (not StatusContexts)

pull_request_rules:
  - name: Auto-merge when all checks pass
    conditions:
      - base=main
      - check-success=test # GitHub Actions check name
      - check-success=deploy # GitHub Actions check name
      - check-success=Run E2E Tests # GitHub Actions check name
    actions:
      merge:
        method: squash
        commit_message_template: "{{title}} (#{{number}})"

# Queue configuration for handling multiple PRs
queue_rules:
  - name: main-queue
    queue_conditions:
      - check-success=test # GitHub Actions check name
      - check-success=deploy # GitHub Actions check name
      - check-success=Run E2E Tests # GitHub Actions check name
