# Mergify configuration for automatic PR merging
# This will auto-merge PRs when all required status checks pass

pull_request_rules:
  - name: Auto-merge when all checks pass
    conditions:
      - base=main
      - status-success=test
      - status-success=deploy
      - status-success=Run E2E Tests
    actions:
      merge:
        method: squash
        commit_message_template: "{{title}} (#{{number}})"
